on:
  schedule:
  - cron:  '*/15 * * * *'
  - cron:  '0 0,1,2,21-23 * 1,2,9-12 TUE'
  - cron:  '0 0,1,2,5 * 1,2,9-12 TUE'
  - cron:  '45 21-23 * 1,2,9-12 THU'
  - cron:  '0 0,1,2 * 1,2,9-12 FRI'
  - cron:  '15,30,45 15-23 * 1,2,9-12 SUN'
  workflow_dispatch:

name: Update Predictions

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PREDICTION_TOKEN }}
      SEBS_GOOGLE_PREDICTION_GAME_COOKIE: ${{ secrets.SEBS_GOOGLE_PREDICTION_GAME_COOKIE }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          extra-repositories: "https://nflverse.r-universe.dev"

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
           extra-packages: |
            local::.
            nflverse/nflreadr
            mrcaseb/pinnacler
            any::pkgload

      - name: Compute and Submit Predictions
        run: Rscript -e 'source("auto/update_prediction_game.R")'
