on:
  schedule:
    - cron:  '0 0,1,2,21-23 * 1,2,9-12 TUE'
    - cron:  '0 0,1,2,5 * 1,2,9-12 TUE'
    - cron:  '45 21-23 * 1,2,9-12 THU'
    - cron:  '0 0,1,2 * 1,2,9-12 FRI'
    - cron:  '45 15-23 * 1,2,9-12 SUN'
  workflow_dispatch:

name: Update Predictions

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PREDICTION_TOKEN }}
      NFLGAMEDATA_TWITTER_GUID: ${{ secrets.NFLGAMEDATA_TWITTER_GUID }}
      PHPSESSID: ${{ secrets.PHPSESSID }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
           extra-packages: |
            nflverse/nflreadr
            mrcaseb/mrcaseb

      - name: Compute and Submit Predictions
        run: Rscript -e 'source("R/update_prediction_game.R")'
